services:
  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./python-server/src:/app/src

  express-server:
    build:
      context: ./express-server
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./express-server/src:/usr/src/app/src
      - /usr/src/app/node_modules
